services:
  - type: web
    name: suno-discord-bot
    env: node
    buildCommand: npm install
    startCommand: node start.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production